### ISSUE TITLE
code not running 

### ISSUE THREAD

**Issue by devraj89** [pujols/Zero-shot-learning-journal#2]
Hi

thanks for the code 

I am however unable to run the demo code within the SynC folder 
demo.m

The function set_path_SynC.m is not defined.
Also, it is throwing an error
```
Not enough input arguments.
Error in SynC_fast (line 17)
[Xtr, Ytr, Xte, Yte, attr2, class_order] = data_loader(dataset, opt, feature_name, 'not');
```
kindly please specify what will be the value of the feature_name arguement?

Please Help!

Devraj

**Comment by pujols** [comment]
Hello,

I was checking the code. The feature_name is defined in Demo_SynC.m, and in SynC/codes there is  set_path_SynC.m. May I know if you directly run Demo_SynC.m?

**Comment by devraj89** [comment]
Hello friend
I am currently unable to look through the code and will get back to you soon.
I am thankful for your prompt response.

Actually, I had run your old GitHub code and got the expected results for the SYNC algorithm in OVO in ZSL paradigm. Then I noticed that you had updated the GitHub repository to include GZSL and I had got confused. Is it possible to put up a few lines regarding how to run the code in the GZSL format?

Thanks again for your prompt reply!

Thanks

**Comment by pujols** [comment]
Hello,

The codes are indeed very similar and you can compare them (ie, Sync_fast.m and Sync_fast_GZSL.m in SynC/codes/). The main difference is in the data split, cross-validation, and metrics.

In the Demo we also include GZSL's demo. You can uncomment that part to run.

Best,

Harry
