### ISSUE TITLE
Codes for evaluating ImageNet "2-hop", "3-hop" and  "all" datasets?

### ISSUE THREAD

**Issue by kaiqiangh** [pujols/Zero-shot-learning-journal#3]
Hi, Thanks for sharing codes. As I checked your reop, you provide ZSL on AwA, CUB, and SUN datasets. However, I cannot find the codes to evaluate ZSL methods on ImageNet (I only can find word2vec.mat for representing class name for ImageNet 1K and "hop-based" datasets). Would you provide these codes somewhere? Thanks.

**Comment by pujols** [comment]
Hi, You may go to Xian's project page: https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/zero-shot-learning/zero-shot-learning-the-good-the-bad-and-the-ugly/.

There you can see the features and the splits. Each split contains a set of class indices, which you can then used to retrieve word2vec as semantic representations. The splits will also tell you what are the classes to test.

The word2vec can be found here: https://github.com/pujols/zero-shot-learning

**Comment by kaiqiangh** [comment]
Thank you very much for providing them!
