### ISSUE TITLE
regarding the attributes

### ISSUE THREAD

**Issue by seyeeet** [pujols/Zero-shot-learning-journal#4]
can you please let me know how/where i can get the attributes (description for each class in words) for each dataset?
what is the typical way for a new dataset?
thanks

**Comment by pujols** [comment]
See below for the responses.

For your first question, please be referred to each data set's original data. What we provided are those after processing. 
http://cvml.ist.ac.at/AwA/
http://cs.brown.edu/~gmpatter/sunattributes.html
http://www.vision.caltech.edu/visipedia/CUB-200.html

For your second question, sorry but I don't quite get it. What do you mean by "typical way"?

**Comment by seyeeet** [comment]
Thank you for your reply.
I mean when I have a new dataset which its attributes are not available, should I do a Mechanical Turk to get the attributes or there is a common way that people get the attributes for new/custom dataset?

**Comment by pujols** [comment]
You probably need to do crowdsourcing. Or, if you have any text descriptions of those classes (e.g., from Wiki, WordNet, or other documentation), you may use them. Note that, our algorithm only needs "class-level" attributes, so you don't need to label attribute for any image but only for that class. You may also use word vectors.

**Comment by seyeeet** [comment]
Thank you!
